// <auto-generated />
namespace Parrilla3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Agrego_Columna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agrego_Columna));
        
        string IMigrationMetadata.Id
        {
            get { return "202008030416414_Agrego_Columna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
